package org.fuin.sokar.runtime;

import java.util.ArrayList;
import java.util.List;
import org.fuin.sokar.core.project.Project;

/**
 * Builds the {@code Containerfile} for a project's task image.
 * <p>
 * Three layers, in this order and for this reason:
 * <ol>
 * <li><strong>base</strong> - the distro image the project chose, plus the unprivileged user and
 *     the fetch tooling every later layer needs;</li>
 * <li><strong>agent</strong> - whatever the selected agent contributes, which is normally a pinned
 *     and digest-verified download of its CLI;</li>
 * <li><strong>project</strong> - the operator's own additions, which is how extra tooling gets
 *     into a box.</li>
 * </ol>
 * Ordering is not cosmetic: the project layer runs last so it can rely on the agent being there,
 * and both run after the user exists so nothing has to guess at ownership.
 * <p>
 * Assembled by hand rather than from a template, on purpose: the byte-exact output is pinned by
 * golden-file tests, so when this moves to a template engine the tests decide whether the result is
 * still the same image.
 */
public final class Containerfile {

    /**
     * How many lines a task's shell session remembers.
     * <p>
     * Pinned so that "what may re-entering claim" has an answer. Ten thousand lines is enough to
     * hold a build somebody walked away from and small enough that a session left open costs
     * nothing worth counting.
     */
    public static final String SCROLLBACK = "10000";

    /**
     * Build argument marking where the agent's layers begin.
     * <p>
     * Passing a value podman has not seen invalidates its cache from this line down, so the
     * agent's tooling is rebuilt and the packages above it are not. Nothing in the image reads it:
     * it exists to be changed.
     */
    public static final String LAYER_EPOCH = "SOKAR_LAYER_EPOCH";

    private Containerfile() {
        throw new UnsupportedOperationException("Utility class");
    }

    /**
     * Renders the Containerfile for a project with no additional layers.
     *
     * @param project The project.
     * @return File content, ending in a line separator.
     */
    /**
     * Returns a short digest of everything about a project that decides its image.
     * <p>
     * <strong>Deliberately not the whole project file.</strong> Egress, limits and the upstream
     * change what a task may do rather than what it is built from, and hashing them would report
     * an image as stale after an edit that could not have changed it - which teaches people to
     * ignore the word.
     * <p>
     * The agent is not in it either: which agent runs is chosen per task rather than per project,
     * so an image is not stale because somebody picked a different one.
     *
     * @param project The project.
     * @return Sixteen hex characters - enough to tell two recipes apart, short enough to read.
     */
    public static String fingerprint(Project project) {
        final String recipe = project.baseImage() + "\u0000"
                + (project.imageSnippet() == null ? "" : project.imageSnippet());
        try {
            final byte[] digest = java.security.MessageDigest.getInstance("SHA-256")
                    .digest(recipe.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            final StringBuilder text = new StringBuilder();
            for (int index = 0; index < 8; index++) {
                text.append(String.format("%02x", digest[index]));
            }
            return text.toString();
        } catch (java.security.NoSuchAlgorithmException ex) {
            throw new IllegalStateException("SHA-256 is required by every Java platform", ex);
        }
    }

    public static String render(Project project) {
        return render(project, ImageLayers.none());
    }

    /**
     * Renders the Containerfile for a project.
     *
     * @param project The project.
     * @param layers What the agent and the project contribute.
     * @return File content, ending in a line separator.
     */
    public static String render(Project project, ImageLayers layers) {

        // One URIs line, space separated, which is what deb822 takes and what apt walks in order.
        final String sources = String.join(" ", project.effectivePackageSources());
        // Only a project that ASKED for sources is refused on a base with no apt. One that asked
        // for nothing gets the default and must still work on fedora and alpine, which is most of
        // them - refusing there would break every non-Debian base for a key nobody wrote.
        final String refusal = project.declaresPackageSources() ? "true" : "false";

        final List<String> lines = new ArrayList<>(List.of(
                "# Generated by Sokar. Do not edit; changes are overwritten on the next build.",
                "FROM " + project.baseImage(),
                "",
                "# curl, CA certificates, git and an ssh client: every pinned agent download needs the",
                "# first two, the workspace is cloned with the third, and an online project pushes to",
                "# a real upstream over ssh with the fourth. A base image cannot be assumed to have",
                "# any of them. Written for the three package managers Sokar's supported bases use;",
                "# a base with none of them must ship these itself, and will fail loudly here rather",
                "# than three layers further down. tmux is here so a session survives leaving it:",
                "# 'sokar task attach' runs it, and a closed window leaves the session running.",
                "USER root",
                "",
                "# Where apt fetches from, before anything fetches. Only the URIs line is replaced,",
                "# never the file rewritten: suites, components and the signing key differ between",
                "# Debian and Ubuntu and between releases, and a file written from guesses breaks an",
                "# image that worked. apt takes the first URI that answers.",
                "#",
                "# Measured on 2026-09-11 during a disruption at Ubuntu's archive, from a machine on",
                "# an ordinary network - a Release file, same host, same minute:",
                "#",
                "#   http://azure.archive.ubuntu.com   HTTP 200    0.18s",
                "#   http://archive.ubuntu.com         HTTP 200   18.86s",
                "#   https://azure.archive.ubuntu.com  HTTP 000   no answer in 25s",
                "#",
                "# The third line is why these are http. Ubuntu's mirrors serve no TLS, and apt takes",
                "# its integrity from the signed Release file rather than from the transport; an https",
                "# URL here would put a source into every image that never answers.",
                "#",
                "# Image builds were hanging until Sokar's own ten-minute cap, on two rented machines",
                "# per run, reporting nothing until it expired. The timeout below is what turns a",
                "# source that does not answer into seconds instead of that.",
                "RUN set -eux; \\",
                "    if command -v apt-get >/dev/null 2>&1; then \\",
                "        printf '%s\\n' 'Acquire::http::Timeout \"20\";' \\",
                "            'Acquire::https::Timeout \"20\";' 'Acquire::Retries \"2\";' \\",
                "            > /etc/apt/apt.conf.d/99-sokar-timeouts; \\",
                "        for f in /etc/apt/sources.list.d/*.sources; do \\",
                "            [ -e \"$f\" ] || continue; \\",
                "            sed -i 's|^URIs:.*|URIs: " + sources + "|' \"$f\"; \\",
                "        done; \\",
                "    elif " + refusal + "; then \\",
                "        echo 'this project names image.package_sources, and " + project.baseImage()
                        + " has no apt to apply them to' >&2; exit 1; \\",
                "    fi",
                "",
                "RUN set -eux; \\",
                "    if command -v curl >/dev/null 2>&1 && command -v git >/dev/null 2>&1 \\",
                "        && command -v ssh >/dev/null 2>&1 && command -v tmux >/dev/null 2>&1; then :; \\",
                "    elif command -v apt-get >/dev/null 2>&1; then \\",
                "        apt-get update && apt-get install -y --no-install-recommends curl ca-certificates git openssh-client tmux \\",
                "        && rm -rf /var/lib/apt/lists/*; \\",
                "    elif command -v apk >/dev/null 2>&1; then apk add --no-cache curl ca-certificates git openssh-client tmux; \\",
                "    elif command -v dnf >/dev/null 2>&1; then dnf install -y curl ca-certificates git openssh-clients tmux && dnf clean all; \\",
                "    else echo 'no curl/git/ssh/tmux and no known package manager in " + project.baseImage() + "' >&2; exit 1; \\",
                "    fi",
                "",
                "",
                "# How much a session remembers, pinned rather than inherited. What 'sokar task",
                "# attach' can honestly claim on returning is exactly this many lines, and a",
                "# figure nobody chose is a figure nobody can state. Written as a file so it is",
                "# readable in the image rather than hidden in a command line.",
                "RUN mkdir -p /etc/sokar \\",
                "    && printf 'set -g history-limit " + SCROLLBACK + "\\n' > /etc/sokar/tmux.conf",
                "",
                "# The agent never runs as root. A rootless podman user namespace already maps this",
                "# to an unprivileged host uid, so this is defense in depth rather than the only line.",
                "# No uid is pinned: 1000 is already taken on several common base images.",
                "RUN id -u agent >/dev/null 2>&1 || useradd --create-home --shell /bin/bash agent",
                "",
                "RUN mkdir -p /workspace && chown agent:agent /workspace"));

        // Everything above is the base image and the packages every task needs. Everything below
        // is the agent's. This ARG is the seam between them: podman invalidates its cache from the
        // line whose text changed, so passing a different value here rebuilds the agent's layers
        // and keeps the package layer - which is the difference between a rebuild that takes
        // seconds and one that downloads a distribution again.
        //
        // It is declared even when no agent contributes anything, so the seam is in the image
        // rather than appearing only when something happens to sit below it.
        lines.add("");
        lines.add("ARG " + LAYER_EPOCH + "=0");

        if (!layers.asRoot().isEmpty()) {
            lines.add("");
            lines.addAll(layers.asRoot());
        }

        lines.add("");
        lines.add("USER agent");
        lines.add("WORKDIR /workspace");
        lines.add("");
        lines.add("# Agents install into ~/.local/bin, which is not on PATH for a non-login");
        lines.add("# shell - and 'podman exec' is one. Without this the agent is present and");
        lines.add("# not findable, which reads as a broken install rather than a missing PATH.");
        lines.add("ENV PATH=/home/agent/.local/bin:/usr/local/bin:/usr/bin:/bin");

        if (!layers.asAgent().isEmpty()) {
            lines.add("");
            lines.addAll(layers.asAgent());
        }

        lines.add("");
        lines.add("LABEL org.fuin.sokar.project=\"" + project.name() + "\"");
        // What this image was built from, so an image built before the project file changed can
        // be told from one that is simply absent. Without it "prepared" says only that something
        // exists, and "this will not be what you expect" is discoverable only by starting work.
        lines.add("LABEL org.fuin.sokar.recipe=\"" + fingerprint(project) + "\"");
        lines.add("LABEL org.fuin.sokar.security-class=\""
                + project.securityClass().name().toLowerCase() + "\"");

        return String.join("\n", lines) + "\n";
    }
}
