package org.fuin.sokar.runtime;

import java.util.ArrayList;
import java.util.List;
import org.fuin.sokar.core.project.Project;

/**
 * Builds the {@code Containerfile} for a project's task image.
 * <p>
 * Three layers, in this order and for this reason:
 * <ol>
 * <li><strong>base</strong> - the distro image the project chose, plus the unprivileged user and
 *     the fetch tooling every later layer needs;</li>
 * <li><strong>agent</strong> - whatever the selected agent contributes, which is normally a pinned
 *     and digest-verified download of its CLI;</li>
 * <li><strong>project</strong> - the operator's own additions, which is how extra tooling gets
 *     into a box.</li>
 * </ol>
 * Ordering is not cosmetic: the project layer runs last so it can rely on the agent being there,
 * and both run after the user exists so nothing has to guess at ownership.
 * <p>
 * Assembled by hand rather than from a template, on purpose: the byte-exact output is pinned by
 * golden-file tests, so when this moves to a template engine the tests decide whether the result is
 * still the same image.
 */
public final class Containerfile {

    private Containerfile() {
        throw new UnsupportedOperationException("Utility class");
    }

    /**
     * Renders the Containerfile for a project with no additional layers.
     *
     * @param project The project.
     * @return File content, ending in a line separator.
     */
    public static String render(Project project) {
        return render(project, ImageLayers.none());
    }

    /**
     * Renders the Containerfile for a project.
     *
     * @param project The project.
     * @param layers What the agent and the project contribute.
     * @return File content, ending in a line separator.
     */
    public static String render(Project project, ImageLayers layers) {

        final List<String> lines = new ArrayList<>(List.of(
                "# Generated by Sokar. Do not edit; changes are overwritten on the next build.",
                "FROM " + project.baseImage(),
                "",
                "# curl and CA certificates, because every pinned agent download needs them and a",
                "# base image cannot be assumed to have either. Written for the three package",
                "# managers Sokar's supported bases use; a base with none of them must ship curl",
                "# itself, and will fail loudly here rather than three layers further down.",
                "USER root",
                "RUN set -eux; \\",
                "    if command -v curl >/dev/null 2>&1; then :; \\",
                "    elif command -v apt-get >/dev/null 2>&1; then \\",
                "        apt-get update && apt-get install -y --no-install-recommends curl ca-certificates \\",
                "        && rm -rf /var/lib/apt/lists/*; \\",
                "    elif command -v apk >/dev/null 2>&1; then apk add --no-cache curl ca-certificates; \\",
                "    elif command -v dnf >/dev/null 2>&1; then dnf install -y curl ca-certificates && dnf clean all; \\",
                "    else echo 'no curl and no known package manager in " + project.baseImage() + "' >&2; exit 1; \\",
                "    fi",
                "",
                "# The agent never runs as root. A rootless podman user namespace already maps this",
                "# to an unprivileged host uid, so this is defence in depth rather than the only line.",
                "# No uid is pinned: 1000 is already taken on several common base images.",
                "RUN id -u agent >/dev/null 2>&1 || useradd --create-home --shell /bin/bash agent",
                "",
                "RUN mkdir -p /workspace && chown agent:agent /workspace"));

        if (!layers.asRoot().isEmpty()) {
            lines.add("");
            lines.addAll(layers.asRoot());
        }

        lines.add("");
        lines.add("USER agent");
        lines.add("WORKDIR /workspace");

        if (!layers.asAgent().isEmpty()) {
            lines.add("");
            lines.addAll(layers.asAgent());
        }

        lines.add("");
        lines.add("LABEL org.fuin.sokar.project=\"" + project.name() + "\"");
        lines.add("LABEL org.fuin.sokar.security-class=\""
                + project.securityClass().name().toLowerCase() + "\"");

        return String.join("\n", lines) + "\n";
    }
}
