package org.fuin.sokar.runtime;

import java.util.ArrayList;
import java.util.List;
import org.fuin.sokar.core.project.Project;

/**
 * Builds the {@code Containerfile} for a project's task image.
 * <p>
 * Three layers, in this order and for this reason:
 * <ol>
 * <li><strong>base</strong> - the distro image the project chose, plus the unprivileged user and
 *     the fetch tooling every later layer needs;</li>
 * <li><strong>agent</strong> - whatever the selected agent contributes, which is normally a pinned
 *     and digest-verified download of its CLI;</li>
 * <li><strong>project</strong> - the operator's own additions, which is how extra tooling gets
 *     into a box.</li>
 * </ol>
 * Ordering is not cosmetic: the project layer runs last so it can rely on the agent being there,
 * and both run after the user exists so nothing has to guess at ownership.
 * <p>
 * Assembled by hand rather than from a template, on purpose: the byte-exact output is pinned by
 * golden-file tests, so when this moves to a template engine the tests decide whether the result is
 * still the same image.
 */
public final class Containerfile {

    /**
     * How many lines a task's shell session remembers.
     * <p>
     * Pinned so that "what may re-entering claim" has an answer. Ten thousand lines is enough to
     * hold a build somebody walked away from and small enough that a session left open costs
     * nothing worth counting.
     */
    public static final String SCROLLBACK = "10000";

    private Containerfile() {
        throw new UnsupportedOperationException("Utility class");
    }

    /**
     * Renders the Containerfile for a project with no additional layers.
     *
     * @param project The project.
     * @return File content, ending in a line separator.
     */
    public static String render(Project project) {
        return render(project, ImageLayers.none());
    }

    /**
     * Renders the Containerfile for a project.
     *
     * @param project The project.
     * @param layers What the agent and the project contribute.
     * @return File content, ending in a line separator.
     */
    public static String render(Project project, ImageLayers layers) {

        final List<String> lines = new ArrayList<>(List.of(
                "# Generated by Sokar. Do not edit; changes are overwritten on the next build.",
                "FROM " + project.baseImage(),
                "",
                "# curl, CA certificates, git and an ssh client: every pinned agent download needs the",
                "# first two, the workspace is cloned with the third, and an online project pushes to",
                "# a real upstream over ssh with the fourth. A base image cannot be assumed to have",
                "# any of them. Written for the three package managers Sokar's supported bases use;",
                "# a base with none of them must ship these itself, and will fail loudly here rather",
                "# than three layers further down. tmux is here so a session survives leaving it:",
                "# 'sokar task attach' runs it, and a closed window leaves the session running.",
                "USER root",
                "RUN set -eux; \\",
                "    if command -v curl >/dev/null 2>&1 && command -v git >/dev/null 2>&1 \\",
                "        && command -v ssh >/dev/null 2>&1 && command -v tmux >/dev/null 2>&1; then :; \\",
                "    elif command -v apt-get >/dev/null 2>&1; then \\",
                "        apt-get update && apt-get install -y --no-install-recommends curl ca-certificates git openssh-client tmux \\",
                "        && rm -rf /var/lib/apt/lists/*; \\",
                "    elif command -v apk >/dev/null 2>&1; then apk add --no-cache curl ca-certificates git openssh-client tmux; \\",
                "    elif command -v dnf >/dev/null 2>&1; then dnf install -y curl ca-certificates git openssh-clients tmux && dnf clean all; \\",
                "    else echo 'no curl/git/ssh/tmux and no known package manager in " + project.baseImage() + "' >&2; exit 1; \\",
                "    fi",
                "",
                "",
                "# How much a session remembers, pinned rather than inherited. What 'sokar task",
                "# attach' can honestly claim on returning is exactly this many lines, and a",
                "# figure nobody chose is a figure nobody can state. Written as a file so it is",
                "# readable in the image rather than hidden in a command line.",
                "RUN mkdir -p /etc/sokar \\",
                "    && printf 'set -g history-limit " + SCROLLBACK + "\\n' > /etc/sokar/tmux.conf",
                "",
                "# The agent never runs as root. A rootless podman user namespace already maps this",
                "# to an unprivileged host uid, so this is defense in depth rather than the only line.",
                "# No uid is pinned: 1000 is already taken on several common base images.",
                "RUN id -u agent >/dev/null 2>&1 || useradd --create-home --shell /bin/bash agent",
                "",
                "RUN mkdir -p /workspace && chown agent:agent /workspace"));

        if (!layers.asRoot().isEmpty()) {
            lines.add("");
            lines.addAll(layers.asRoot());
        }

        lines.add("");
        lines.add("USER agent");
        lines.add("WORKDIR /workspace");
        lines.add("");
        lines.add("# Agents install into ~/.local/bin, which is not on PATH for a non-login");
        lines.add("# shell - and 'podman exec' is one. Without this the agent is present and");
        lines.add("# not findable, which reads as a broken install rather than a missing PATH.");
        lines.add("ENV PATH=/home/agent/.local/bin:/usr/local/bin:/usr/bin:/bin");

        if (!layers.asAgent().isEmpty()) {
            lines.add("");
            lines.addAll(layers.asAgent());
        }

        lines.add("");
        lines.add("LABEL org.fuin.sokar.project=\"" + project.name() + "\"");
        lines.add("LABEL org.fuin.sokar.security-class=\""
                + project.securityClass().name().toLowerCase() + "\"");

        return String.join("\n", lines) + "\n";
    }
}
