package org.fuin.sokar.runtime;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.fuin.sokar.wire.Json;
import org.fuin.sokar.wire.Sidecar;

/**
 * Installs the OCI hook descriptors podman reads before creating a container.
 * <p>
 * Installation is per operator, into {@code $XDG_CONFIG_HOME/containers/oci/hooks.d}, and needs no
 * privileges. The descriptors are rewritten on every install so that an upgrade cannot leave a
 * descriptor pointing at a binary that no longer exists.
 * <p>
 * <strong>Every descriptor is gated on the sidecar annotation.</strong> Without that gate these
 * hooks would fire for every container the operator runs, including ones that have nothing to do
 * with Sokar - and the nft hook would then refuse to start them.
 */
public class HookInstaller {

    /** Stage at which all three hooks run before the container starts. */
    public static final String CREATE_RUNTIME = "createRuntime";

    /** Stage at which cleanup runs after the container is gone. */
    public static final String POSTSTOP = "poststop";

    private final Path hooksDirectory;

    private final Path binaryDirectory;

    /**
     * Constructor.
     *
     * @param hooksDirectory Directory podman reads descriptors from.
     * @param binaryDirectory Directory the hook binaries are installed in.
     */
    public HookInstaller(Path hooksDirectory, Path binaryDirectory) {
        this.hooksDirectory = hooksDirectory;
        this.binaryDirectory = binaryDirectory;
    }

    /**
     * Returns the descriptors that would be installed, keyed by file name.
     *
     * @return Descriptor documents.
     */
    public Map<String, String> descriptors() {
        final Map<String, String> all = new java.util.LinkedHashMap<>();
        for (final Map.Entry<String, List<String>> entry : HOOKS.entrySet()) {
            for (final String stage : entry.getValue()) {
                all.put(entry.getKey() + "-" + stage + ".json", descriptor(entry.getKey(), stage));
            }
        }
        return Map.copyOf(all);
    }

    /** The hook binaries and the stages each of them runs at. */
    private static final Map<String, List<String>> HOOKS = Map.of(
            "sokar-hook-nft", List.of(CREATE_RUNTIME, POSTSTOP),
            "sokar-hook-supervisor", List.of(CREATE_RUNTIME, POSTSTOP),
            "sokar-hook-reader", List.of(CREATE_RUNTIME, POSTSTOP));

    private String descriptor(String binary, String stage) {

        final Path executable = binaryDirectory.resolve(binary);

        // One descriptor per stage. The runtime does not tell a hook which stage fired, so the
        // stage has to be baked into the arguments - which means a separate file for each.
        final Map<String, Object> hook = new java.util.LinkedHashMap<>();
        hook.put("path", executable.toString());
        hook.put("args", List.of(binary, stage));
        hook.put("timeout", Integer.valueOf(30));

        final Map<String, Object> when = new java.util.LinkedHashMap<>();
        when.put("annotations", Map.of(quoteForMatch(Sidecar.ANNOTATION), ".*"));

        final Map<String, Object> root = new java.util.LinkedHashMap<>();
        root.put("version", "1.0.0");
        root.put("hook", hook);
        root.put("when", when);
        root.put("stages", List.of(stage));

        return Json.write(root);
    }

    private static String quoteForMatch(String annotation) {
        // podman treats the key as a regular expression. The dots in the annotation would
        // otherwise match any character, so a foreign annotation could switch the hooks on.
        return annotation.replace(".", "\\.");
    }

    /**
     * Returns the podman drop-in that points podman at the hook directory.
     * <p>
     * A drop-in rather than an edit of {@code containers.conf}: podman's own default
     * {@code hooks_dir} is a root-owned system path, so an unprivileged operator must add one, and
     * rewriting a configuration file Sokar does not own is how installers destroy settings.
     *
     * @return File content.
     */
    public String podmanDropIn() {
        return """
                # Generated by 'sokar setup'. Remove with 'sokar setup --uninstall'.
                # podman's built-in hooks_dir is a system path that needs root, so a rootless
                # installation has to add its own.
                [engine]
                hooks_dir = ["%s"]
                """.formatted(hooksDirectory);
    }

    /**
     * Returns the path of the podman drop-in.
     *
     * @return Drop-in file.
     */
    public Path dropInFile() {
        // hooks.d sits in oci/ inside the containers directory, so two levels up always exists.
        return hooksDirectory.resolve("../../containers.conf.d/50-sokar.conf").normalize();
    }

    /**
     * What an operator's podman will actually do with Sokar's hooks.
     * <p>
     * Distinguished rather than collapsed into a boolean, because the repairs differ: a machine
     * that never ran {@code sokar setup} needs it run, while descriptors pointing at binaries that
     * are gone is what a package upgrade leaves behind.
     */
    public enum Registration {

        /** Every descriptor is in place, in a directory podman reads, naming binaries that exist. */
        ACTIVE,

        /** No descriptors, or no drop-in: {@code sokar setup} has not been run for this user. */
        MISSING,

        /** Descriptors are installed but name binaries that are not there any more. */
        DANGLING,

        /** Installed, but another drop-in sorts later and points {@code hooks_dir} elsewhere. */
        SHADOWED,

        /**
         * Installed, but not what this version of Sokar writes.
         * <p>
         * What an upgrade leaves behind. The package replaces the binaries and never touches
         * these files, and nothing runs {@code sokar setup} for the operator - so a release that
         * changes what a descriptor says leaves the old one in place, and every check that asks
         * only whether the files are <em>there</em> answers yes.
         */
        STALE
    }

    /**
     * Returns what podman will do with Sokar's hooks on this machine.
     * <p>
     * The question is what the runtime reads, not what Sokar would write: a descriptor in a
     * directory no {@code hooks_dir} names is not installed, however correct its contents.
     *
     * @return The state, worst first: a machine can be several of these at once and the most
     *         damaging is the one worth reporting.
     */
    public Registration registration() {

        if (!Files.isRegularFile(dropInFile())) {
            return Registration.MISSING;
        }
        for (final String name : descriptors().keySet()) {
            if (!Files.isRegularFile(hooksDirectory.resolve(name))) {
                return Registration.MISSING;
            }
        }
        if (!effectiveHooksDirectories().contains(hooksDirectory.toString())) {
            return Registration.SHADOWED;
        }
        if (!binariesPresent()) {
            return Registration.DANGLING;
        }
        // Last, because it is the least definite: the three above are all "the hooks will not
        // run", while this one is "they will run, and not necessarily as this version intends".
        return outdated().isEmpty() ? Registration.ACTIVE : Registration.STALE;
    }

    /**
     * Returns the installed files whose contents are not what this version writes.
     * <p>
     * <strong>Presence was never enough.</strong> A descriptor's contents carry the path of the
     * hook binary, the arguments it is given and the annotation it fires on; a release can change
     * any of those without changing a file name, and then the operator's podman goes on running
     * the old one. The visible failure is a container that starts without its firewall, which
     * looks exactly like a container that started correctly.
     * <p>
     * A file that was hand-edited counts as outdated too, and deliberately: this answers what
     * podman will read against what this version means, and there is no third thing it could be.
     *
     * @return Paths that {@code sokar setup} would rewrite, empty when everything matches.
     */
    public List<Path> outdated() {
        final List<Path> differing = new ArrayList<>();
        for (final Map.Entry<String, String> entry : descriptors().entrySet()) {
            final Path file = hooksDirectory.resolve(entry.getKey());
            if (!contentIs(file, entry.getValue() + "\n")) {
                differing.add(file);
            }
        }
        if (!contentIs(dropInFile(), podmanDropIn())) {
            differing.add(dropInFile());
        }
        differing.sort(Path::compareTo);
        return List.copyOf(differing);
    }

    private static boolean contentIs(Path file, String expected) {
        try {
            return Files.exists(file) && Files.readString(file, StandardCharsets.UTF_8)
                    .equals(expected);
        } catch (IOException ex) {
            // Unreadable is not "the same as what we would write". Treating it as a match would
            // turn a broken installation into a silent one.
            return false;
        }
    }

    /**
     * Returns the hook directories podman ends up with, after every drop-in has had its say.
     * <p>
     * Drop-ins are read in name order and each {@code hooks_dir} replaces the last, so a file
     * sorting after Sokar's own silently switches the hooks off. That is invisible in every other
     * way: the descriptors are still there and still correct.
     *
     * @return Directories named by the winning drop-in, empty if none names any.
     */
    public List<String> effectiveHooksDirectories() {

        final Path directory = java.util.Objects.requireNonNull(dropInFile().getParent(), "a drop-in is in a directory");
        if (!Files.isDirectory(directory)) {
            return List.of();
        }
        List<String> winner = List.of();
        try (java.util.stream.Stream<Path> files = Files.list(directory)) {
            for (final Path file : files.filter(path -> path.toString().endsWith(".conf"))
                    .sorted(java.util.Comparator.comparing(path -> path.getFileName().toString()))
                    .toList()) {
                final List<String> named = hooksDirectoriesIn(file);
                if (!named.isEmpty()) {
                    winner = named;
                }
            }
        } catch (IOException ex) {
            return List.of();
        }
        return winner;
    }

    private static List<String> hooksDirectoriesIn(Path file) {
        try {
            for (final String line : Files.readAllLines(file)) {
                final String text = line.strip();
                if (text.startsWith("#") || !text.startsWith("hooks_dir")) {
                    continue;
                }
                final int bracket = text.indexOf('[');
                if (bracket < 0) {
                    continue;
                }
                return java.util.Arrays.stream(
                                text.substring(bracket + 1).replace("]", "").split(","))
                        .map(entry -> entry.strip().replace("\"", ""))
                        .filter(entry -> !entry.isEmpty())
                        .toList();
            }
        } catch (IOException ex) {
            return List.of();
        }
        return List.of();
    }

    /**
     * Writes the descriptors, replacing any that are already there.
     *
     * @return Paths of the written files.
     * @throws IOException If a file cannot be written.
     */
    public List<Path> install() throws IOException {
        Files.createDirectories(hooksDirectory);
        final List<Path> written = new java.util.ArrayList<>();
        for (final Map.Entry<String, String> entry : descriptors().entrySet()) {
            final Path file = hooksDirectory.resolve(entry.getKey());
            Files.writeString(file, entry.getValue() + "\n", StandardCharsets.UTF_8);
            written.add(file);
        }
        final Path dropIn = dropInFile();
        Files.createDirectories(dropIn.getParent());
        Files.writeString(dropIn, podmanDropIn(), StandardCharsets.UTF_8);
        written.add(dropIn);
        written.sort(Path::compareTo);
        return List.copyOf(written);
    }

    /**
     * Removes the descriptors.
     *
     * @return Number of files removed.
     * @throws IOException If a file cannot be removed.
     */
    public List<Path> uninstall() throws IOException {
        final List<Path> removed = new ArrayList<>();
        for (final String name : descriptors().keySet()) {
            final Path file = hooksDirectory.resolve(name);
            if (Files.deleteIfExists(file)) {
                removed.add(file);
            }
        }
        // In a different directory from the rest, which is why this returns paths rather than a
        // count: a count with one directory beside it named the wrong place for this one file,
        // and where things went is the whole point of saying anything.
        if (Files.deleteIfExists(dropInFile())) {
            removed.add(dropInFile());
        }
        return List.copyOf(removed);
    }

    /**
     * Tells whether every hook binary the descriptors point at exists and can be executed.
     *
     * @return {@code true} if all three binaries are in place.
     */
    public boolean binariesPresent() {
        return List.of("sokar-hook-nft", "sokar-hook-supervisor", "sokar-hook-reader").stream()
                .map(binaryDirectory::resolve)
                .allMatch(Files::isExecutable);
    }
}
