# Generated by Sokar. Do not edit; changes are overwritten on the next build.
FROM ubuntu:24.04

# The agent never runs as root. A rootless podman user namespace already maps this
# to an unprivileged host uid, so this is defence in depth rather than the only line.
# No uid is pinned: 1000 is already taken on several common base images.
RUN id -u agent >/dev/null 2>&1 || useradd --create-home --shell /bin/bash agent

RUN mkdir -p /workspace && chown agent:agent /workspace

USER agent
WORKDIR /workspace

LABEL org.fuin.sokar.project="uc"
LABEL org.fuin.sokar.security-class="guarded"
