# Generated by Sokar. Do not edit; changes are overwritten on the next build.
FROM ubuntu:24.04

# curl and CA certificates, because every pinned agent download needs them and a
# base image cannot be assumed to have either. Written for the three package
# managers Sokar's supported bases use; a base with none of them must ship curl
# itself, and will fail loudly here rather than three layers further down.
USER root
RUN set -eux; \
    if command -v curl >/dev/null 2>&1; then :; \
    elif command -v apt-get >/dev/null 2>&1; then \
        apt-get update && apt-get install -y --no-install-recommends curl ca-certificates \
        && rm -rf /var/lib/apt/lists/*; \
    elif command -v apk >/dev/null 2>&1; then apk add --no-cache curl ca-certificates; \
    elif command -v dnf >/dev/null 2>&1; then dnf install -y curl ca-certificates && dnf clean all; \
    else echo 'no curl and no known package manager in ubuntu:24.04' >&2; exit 1; \
    fi

# The agent never runs as root. A rootless podman user namespace already maps this
# to an unprivileged host uid, so this is defence in depth rather than the only line.
# No uid is pinned: 1000 is already taken on several common base images.
RUN id -u agent >/dev/null 2>&1 || useradd --create-home --shell /bin/bash agent

RUN mkdir -p /workspace && chown agent:agent /workspace

USER agent
WORKDIR /workspace

LABEL org.fuin.sokar.project="uc"
LABEL org.fuin.sokar.security-class="guarded"
