# Generated by Sokar. Do not edit; changes are overwritten on the next build.
FROM ubuntu:24.04

# curl, CA certificates, git and an ssh client: every pinned agent download needs the
# first two, the workspace is cloned with the third, and an online project pushes to
# a real upstream over ssh with the fourth. A base image cannot be assumed to have
# any of them. Written for the three package managers Sokar's supported bases use;
# a base with none of them must ship these itself, and will fail loudly here rather
# than three layers further down. tmux is here so a session survives leaving it:
# 'sokar task attach' runs it, and a closed window leaves the session running.
USER root

# Where apt fetches from, before anything fetches. Only the URIs line is replaced,
# never the file rewritten: suites, components and the signing key differ between
# Debian and Ubuntu and between releases, and a file written from guesses breaks an
# image that worked.
#
# Measured 2026-09-11 on a rented machine of the kind this build runs on, pulling a
# 19 MB package index while Ubuntu's archive was disrupted:
#
#   azure.archive.ubuntu.com   19.3 MB in  0.08s   230 MB/s
#   archive.ubuntu.com          2.2 MB in 60.00s    37 kB/s  (timed out)
#
# One source rather than a list: apt spreads requests over the URIs it is given
# instead of keeping the second in reserve, so a crawling mirror beside a fast one
# costs every build. With both, apt-get update took 4m03s for 65 MB of indices and
# the build hit Sokar's ten-minute cap. Somebody whose network prefers another
# mirror names it with image.package_sources.
#
# http, not https: Ubuntu's mirrors serve no TLS, and apt takes its integrity from
# the signed Release file rather than from the transport.
RUN set -eux; \
    if command -v apt-get >/dev/null 2>&1; then \
        printf '%s\n' 'Acquire::http::Timeout "20";' \
            'Acquire::https::Timeout "20";' 'Acquire::Retries "2";' \
            > /etc/apt/apt.conf.d/99-sokar-timeouts; \
        for f in /etc/apt/sources.list.d/*.sources; do \
            [ -e "$f" ] || continue; \
            sed -i 's|^URIs:.*|URIs: http://azure.archive.ubuntu.com/ubuntu/|' "$f"; \
        done; \
    elif false; then \
        echo 'this project names image.package_sources, and ubuntu:24.04 has no apt to apply them to' >&2; exit 1; \
    fi

RUN set -eux; \
    if command -v curl >/dev/null 2>&1 && command -v git >/dev/null 2>&1 \
        && command -v ssh >/dev/null 2>&1 && command -v tmux >/dev/null 2>&1; then :; \
    elif command -v apt-get >/dev/null 2>&1; then \
        apt-get update && apt-get install -y --no-install-recommends curl ca-certificates git openssh-client tmux \
        && rm -rf /var/lib/apt/lists/*; \
    elif command -v apk >/dev/null 2>&1; then apk add --no-cache curl ca-certificates git openssh-client tmux; \
    elif command -v dnf >/dev/null 2>&1; then dnf install -y curl ca-certificates git openssh-clients tmux && dnf clean all; \
    else echo 'no curl/git/ssh/tmux and no known package manager in ubuntu:24.04' >&2; exit 1; \
    fi


# How much a session remembers, pinned rather than inherited. What 'sokar task
# attach' can honestly claim on returning is exactly this many lines, and a
# figure nobody chose is a figure nobody can state. Written as a file so it is
# readable in the image rather than hidden in a command line.
#
# The terminal a program INSIDE the session sees is tmux's, not the one outside,
# so passing a 256-colour TERM into the container is only half of it: tmux's own
# default is 'screen', which is eight. Chosen at build time by asking this image
# what it can resolve, because a default-terminal naming an entry the image lacks
# is worse than the eight colours it was meant to replace.
#
# Extended keys always, so a modified Enter reaches an agent: with them off, agents
# in a task warned at every start that Shift+Enter may not work, and 'on' passed them
# only to a program asking in a way tmux 3.4 knows, which the agents do not. '-q',
# because a tmux older than the option would otherwise complain about the line.
# And xterm-like clients are told they take modified keys: tmux asks a client for
# them only when its terminal-features say so, and a client that answers the
# terminal queries plainly - the interface's does - is otherwise never asked.
#
# The rest makes a session feel like the terminal outside, each line for a difference
# measured on 2026-10-09 with tmux 3.4 behind 'podman exec -it': Esc arrived 501 ms
# late; Shift+Enter and focus events never arrived; truecolour, the clipboard, links
# and the title were dropped on the way out; and the wheel reached an agent in the
# alternate screen as nothing it had asked for. Shift+PageUp scrolls the session's
# history where the agent writes into it, and goes to the agent where it draws its
# own screen. Options an older tmux lacks are set with '-q'.
#
# Then a person's own file, copied in when a task starts, and last what Sokar itself
# depends on, so nothing in that file changes it unawares.
RUN mkdir -p /etc/sokar \
    && printf '%s\n' \
        'set -sg escape-time 10' \
        'set -gq extended-keys always' \
        'set -g focus-events on' \
        'set -g set-clipboard on' \
        'set -gq allow-passthrough on' \
        'set -asq terminal-features "xterm*:RGB:clipboard:hyperlinks:focus:title:extkeys"' \
        'set -g set-titles on' \
        'set -g set-titles-string "#T"' \
        'set -g mouse on' \
        'bind -n S-PPage if -F "#{alternate_on}" "send-keys S-PPage" "copy-mode -eu"' \
        'source-file -q /etc/sokar/account-tmux.conf' \
        'source-file /etc/sokar/tmux-required.conf' \
        > /etc/sokar/tmux.conf \
    && printf 'set -g history-limit 10000\n' > /etc/sokar/tmux-required.conf \
    && if infocmp tmux-256color >/dev/null 2>&1; then \
        printf 'set -g default-terminal "tmux-256color"\n' >> /etc/sokar/tmux-required.conf; \
    elif infocmp screen-256color >/dev/null 2>&1; then \
        printf 'set -g default-terminal "screen-256color"\n' >> /etc/sokar/tmux-required.conf; \
    fi

# The agent never runs as root. A rootless podman user namespace already maps this
# to an unprivileged host uid, so this is defense in depth rather than the only line.
# No uid is pinned: 1000 is already taken on several common base images.
RUN id -u agent >/dev/null 2>&1 || useradd --create-home --shell /bin/bash agent

RUN mkdir -p /workspace && chown agent:agent /workspace

# Files handed to a running task land in /sokar/files, which holds nothing else, so an
# agent can be told to read all of it. /sokar is Sokar's: a base image that already has
# it is refused rather than shared with. A file arrives in /sokar/.incoming, where the
# agent cannot look, and is renamed into place whole. Both belong to root, so the agent
# reads what it was given and cannot change or remove it.
RUN if [ -e /sokar ]; then \
        echo 'sokar: the base image ubuntu:24.04 already has /sokar, which Sokar keeps for files handed to a task - use a base image without it' >&2; \
        exit 1; \
    fi \
    && mkdir -p /sokar/files /sokar/.incoming \
    && chmod 0755 /sokar /sokar/files && chmod 0700 /sokar/.incoming

ARG SOKAR_LAYER_EPOCH=0

USER agent
WORKDIR /workspace

# Agents install into ~/.local/bin, which is not on PATH for a non-login
# shell - and 'podman exec' is one. Without this the agent is present and
# not findable, which reads as a broken install rather than a missing PATH.
ENV PATH=/home/agent/.local/bin:/usr/local/bin:/usr/bin:/bin

# Without a UTF-8 locale an agent's interface arrives as underscores.
ENV LANG=C.UTF-8

LABEL org.fuin.sokar.project="uc"
LABEL org.fuin.sokar.recipe="565f4655c57ba02d"
LABEL org.fuin.sokar.security-class="guarded"
