package org.fuin.sokar.gate;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;
import org.junit.jupiter.api.Test;

/**
 * Tests for {@link ReviewRanking}: what a person reads first, without git.
 */
class ReviewRankingTest {

    private static ReviewRanking.Change modified(String path) {
        return new ReviewRanking.Change(path, "M", "100644", "100644", 1, 1, false, "text");
    }

    @Test
    void namesTheKindsThatAreDangerousWhoeverMadeThem() {
        assertThat(ReviewRanking.dangerByPath(".github/workflows/build.yml")).contains("CI definition");
        assertThat(ReviewRanking.dangerByPath(".gitlab-ci.yml")).contains("CI definition");
        assertThat(ReviewRanking.dangerByPath("services/api/pom.xml")).contains("build script");
        assertThat(ReviewRanking.dangerByPath("Makefile")).contains("build script");
        assertThat(ReviewRanking.dangerByPath("web/package-lock.json")).contains("lockfile");
        assertThat(ReviewRanking.dangerByPath("requirements-dev.txt")).contains("lockfile");
        assertThat(ReviewRanking.dangerByPath(".husky/pre-commit")).contains("checked out");
        assertThat(ReviewRanking.dangerByPath(".gitattributes")).contains("checked out");
        assertThat(ReviewRanking.dangerByPath("docker-compose.override.yml")).contains("build script");
    }

    @Test
    void leavesAnOrdinaryFileOrdinary() {
        assertThat(ReviewRanking.dangerByPath("src/main/java/App.java")).isNull();
        assertThat(ReviewRanking.dangerByPath("docs/workflows.md")).isNull();
        assertThat(ReviewRanking.dangerByPath("my-pom.xml.txt")).isNull();
    }

    @Test
    void aFileMadeExecutableOrALinkIsDangerousWhereverItIs() {
        assertThat(ReviewRanking.danger(new ReviewRanking.Change("tools/run", "M", "100644", "100755", 0, 0,
                false, "x"))).isEqualTo("made executable");
        assertThat(ReviewRanking.danger(new ReviewRanking.Change("data", "A", "000000", "120000", 1, 0,
                false, "/etc/passwd"))).contains("symbolic link");
    }

    @Test
    void aDangerousFileIsNeverFiledAsReformattingOrGenerated() {
        // A workflow reformatted, or one that calls itself generated, is still a workflow.
        final List<ReviewRanking.File> files = ReviewRanking.rank(List.of(
                new ReviewRanking.Change(".github/workflows/ci.yml", "M", "100644", "100644", 3, 3, true,
                        "# DO NOT EDIT")));

        assertThat(files.getFirst().rank()).isEqualTo(ReviewRanking.Rank.DANGEROUS);
    }

    @Test
    void ordersDangerousThenOrdinaryThenGeneratedThenReformatting() {
        final List<ReviewRanking.File> files = ReviewRanking.rank(List.of(
                new ReviewRanking.Change("a.txt", "M", "100644", "100644", 400, 400, true, "x"),
                new ReviewRanking.Change("b.js", "M", "100644", "100644", 1, 0, false, "/* @generated */"),
                modified("c.txt"),
                modified("go.mod")));

        assertThat(files).extracting(ReviewRanking.File::path).containsExactly("go.mod", "c.txt", "b.js", "a.txt");
    }

    @Test
    void knowsTheGeneratedMarkersOfTheCommonGenerators() {
        // Dart's build_runner, measured by Agent Frontend: "// GENERATED CODE - DO NOT MODIFY BY HAND".
        for (final String head : List.of("// GENERATED CODE - DO NOT MODIFY BY HAND", "// Code generated by x. DO NOT EDIT.",
                "/* @generated */")) {
            assertThat(ReviewRanking.rank(List.of(new ReviewRanking.Change("lib/money.g.dart", "A", "000000", "100644",
                    9, 0, false, head))).getFirst().rank()).as(head).isEqualTo(ReviewRanking.Rank.GENERATED);
        }
    }

    @Test
    void escapesAPathSoGitReadsItAsItselfInTheOrderFile() {
        final String order = ReviewRanking.orderFile(List.of(
                new ReviewRanking.File("odd[1]*.txt", "M", 1, 1, ReviewRanking.Rank.ORDINARY, "")));

        assertThat(order).isEqualTo("odd\\[1]\\*.txt\n");
    }
}
