package org.fuin.sokar.shield;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.fuin.sokar.core.project.SecurityClass;

/**
 * Generates the nftables ruleset loaded into a task container's network namespace.
 * <p>
 * The ruleset is generated on the host and written to a file before the container exists. The nft
 * hook only pipes it into {@code nft} inside the container's namespace, so the hook needs no
 * knowledge of policy and the policy can be inspected by an operator before anything runs.
 * <p>
 * <strong>The output chain drops by default.</strong> Everything else in this class widens that,
 * never narrows it, so a bug that loses a rule fails towards no connectivity rather than towards
 * an open container.
 */
public class NftRuleset {

    /** NFLOG group the reader listens on. */
    public static final int NFLOG_GROUP = 1;

    /** Log prefix on every dropped packet, used to recognise Sokar's own events. */
    public static final String DROP_PREFIX = "sokar-drop";

    private final SecurityClass securityClass;

    private final Set<String> allowedV4 = new LinkedHashSet<>();

    private final Set<String> allowedV6 = new LinkedHashSet<>();

    private final Set<String> resolvers = new LinkedHashSet<>();

    /**
     * Constructor with the project's security class.
     *
     * @param securityClass Decides whether any egress is possible at all.
     */
    public NftRuleset(SecurityClass securityClass) {
        this.securityClass = securityClass;
    }

    /**
     * Allows egress to an IPv4 address or network.
     *
     * @param cidr Address or CIDR block.
     * @return This instance.
     */
    public NftRuleset allowV4(String cidr) {
        allowedV4.add(cidr);
        return this;
    }

    /**
     * Allows egress to an IPv6 address or network.
     *
     * @param cidr Address or CIDR block.
     * @return This instance.
     */
    public NftRuleset allowV6(String cidr) {
        allowedV6.add(cidr);
        return this;
    }

    /**
     * Allows DNS queries to a resolver.
     *
     * @param address IPv4 address of the resolver.
     * @return This instance.
     */
    public NftRuleset resolver(String address) {
        resolvers.add(address);
        return this;
    }

    /**
     * Renders the ruleset.
     *
     * @return File content, ending in a line separator.
     */
    public String render() {

        final List<String> lines = new ArrayList<>();

        lines.add("# Generated by Sokar for security class '"
                + securityClass.name().toLowerCase() + "'. Do not edit.");
        lines.add("# Loaded inside the container's network namespace by the nft hook.");
        lines.add("");
        lines.add("table inet sokar {");
        lines.add("");
        lines.add("    set allowed_v4 {");
        lines.add("        type ipv4_addr");
        lines.add("        flags interval");
        lines.add(elements(allowedV4));
        lines.add("    }");
        lines.add("");
        lines.add("    set allowed_v6 {");
        lines.add("        type ipv6_addr");
        lines.add("        flags interval");
        lines.add(elements(allowedV6));
        lines.add("    }");
        lines.add("");
        lines.add("    chain output {");
        lines.add("        type filter hook output priority filter; policy drop;");
        lines.add("");
        lines.add("        # A reply to something the container already sent is not a new decision.");
        lines.add("        ct state established,related accept");
        lines.add("");
        lines.add("        # Loopback is inside the namespace, so this reaches nothing outside it.");
        lines.add("        oif \"lo\" accept");

        if (securityClass != SecurityClass.OFFLINE) {
            if (!resolvers.isEmpty()) {
                lines.add("");
                lines.add("        # DNS goes to the resolver Sokar runs, and nowhere else.");
                for (final String resolver : resolvers) {
                    lines.add("        ip daddr " + resolver + " udp dport 53 accept");
                    lines.add("        ip daddr " + resolver + " tcp dport 53 accept");
                }
            }
            lines.add("");
            lines.add("        ip daddr @allowed_v4 accept");
            lines.add("        ip6 daddr @allowed_v6 accept");
        } else {
            lines.add("");
            lines.add("        # Security class 'offline': no egress set is consulted at all.");
        }

        lines.add("");
        lines.add("        # Everything that reaches this point is dropped by the chain policy.");
        lines.add("        # It is logged first, which is what the clearance prompt is built on.");
        lines.add("        log prefix \"" + DROP_PREFIX + " \" group " + NFLOG_GROUP);
        lines.add("    }");
        lines.add("}");

        return String.join("\n", lines) + "\n";
    }

    private static String elements(Set<String> values) {
        if (values.isEmpty()) {
            return "        # (no entries)";
        }
        return "        elements = { " + String.join(", ", values) + " }";
    }
}
